# Generated by Django 3.2.5 on 2021-10-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='Symbol')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('date', models.CharField(default='1996-01-01', max_length=15, verbose_name='Date')),
                ('category', models.CharField(default=' ', max_length=15, verbose_name='Category')),
                ('profit', models.FloatField(default=0, verbose_name='Profit')),
            ],
        ),
    ]
