# Generated by Django 3.2.5 on 2021-10-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmodel',
            name='capital',
            field=models.IntegerField(default=0, verbose_name='Capital'),
        ),
    ]
