# Generated by Django 3.2.5 on 2021-10-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockmodel_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmodel',
            name='book_value',
            field=models.FloatField(default=0, verbose_name='Book_Value'),
        ),
    ]
