# Generated by Django 3.2.5 on 2021-10-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockmodel_book_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmodel',
            name='book_value',
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='shares_outstanding',
            field=models.FloatField(default=0, verbose_name='Shares_Outstanding'),
        ),
    ]
