# Generated by Django 3.2.5 on 2021-10-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20211018_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmodel',
            name='capital',
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='book_value',
            field=models.FloatField(default=0, verbose_name='Book_Value'),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='shares_outstanding',
            field=models.IntegerField(default=0, verbose_name='Shares_Outstanding'),
        ),
    ]
