# Generated by Django 3.2.5 on 2021-10-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20211018_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmodel',
            name='eps',
            field=models.FloatField(default=0, verbose_name='Eps'),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='category',
            field=models.CharField(default=' ', max_length=25, verbose_name='Category'),
        ),
    ]
