# Generated by Django 3.2.5 on 2021-10-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20211021_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmodel',
            name='roe',
            field=models.FloatField(default=0, verbose_name='Roe'),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='profit',
            field=models.FloatField(blank=True, default=0, verbose_name='Profit'),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='shares_outstanding',
            field=models.IntegerField(blank=True, default=0, verbose_name='Shares_Outstanding'),
        ),
    ]
