# Generated by Django 3.2.5 on 2021-11-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20211022_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmodel',
            name='year',
            field=models.CharField(default='', max_length=25, verbose_name='year'),
        ),
    ]
